"
" Older vimrc in case some OS does not support lua. In that case I use a
" simplified configuration for all tasks. It is very likely that I won't
" do heavy development on those OS. Otherwise I could just install a
" newer version that supports lua and use my normal configuration.
" 

filetype plugin on
syntax enable
syntax on
set autoindent
set belloff=all
set showcmd				      " Show (partial) command in status line.
set showmatch				  " Show matching brackets.
set ignorecase				  " Do case insensitive matching
set incsearch				  " Incremental search -> while searching you get the results
set autowrite				  " Automatically save before commands like :next and :make
set mouse=a				      " Enable mouse usage (all modes)
set path+=** 				  " searches in the folders if I use :find
set wildmenu 				  " uses a menu so that I can select the file if I use <tab> for completion in
					          " :find and more than one file has been found
set relativenumber	     	  " sets relative numbers
set number				      " sets number at the current line
set clipboard=unnamedplus	  " activates clipboard ?
set hidden
set nowrap 				      " code can go down go out of screen
let mapleader=' '
set encoding=utf-8
set backspace=indent,eol,start 	  " removing the restriction of the backspace 
                                  " so that it it is possible to delete previously 
                                  " entered code
set noswapfile                    " no swap file is going to get created

set expandtab
set tabstop=4                     " show existing tab with X spaces width
set softtabstop=0                 " width of indentation span
set shiftwidth=4                  " when indenting with '>', use X spaces width


" not too long lines (max. 80 characters)
set colorcolumn=80

" my universal mapping
nnoremap ,unfold :set foldlevel=100<cr>	
nnoremap ,all ggvg
nnoremap ,clear ggVGx
nnoremap <leader>h :wincmd h<cr> 		" switch windows 
nnoremap <leader>j :wincmd j<cr> 		" switch windows
nnoremap <leader>k :wincmd k<cr> 		" switch windows
nnoremap <leader>l :wincmd l<cr> 		" switch windows 

" netrw (https://vonheikemen.github.io/devlog/tools/using-netrw-vim-builtin-file-explorer/)
let g:netrw_preview=1                           " preview is on right side when clicking p in netrw
let g:netrw_winsize= 30                         " 30% window size
let g:netrw_banner= 0                           " If you want to see the banner again, type I
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'  " hide dot files

function! NetrwMapping()
    " go back in history
    nmap <buffer> H u
    " go up a directory
    nmap <buffer> h -^
    " go into a directory / open file
    nmap <buffer> l <CR>

    " show or hide dot file
    nmap <buffer> . gh
    " Close the preview window
    nmap <buffer> P <C-w>z

    " Open file and close netrw
    nmap <buffer> L <CR>:Lexplore<CR>
    " close netrw
    nmap <buffer> <Leader>dd :Lexplore<CR>
endfunction
augroup netrw_mapping
  autocmd!
  autocmd filetype netrw call NetrwMapping()
augroup END

" Open netrw in directory of current file
nnoremap <leader>df :Lexplore %:p:h<cr>
" Open netrw in current working directory
nnoremap <leader>dd :Lexplore<cr>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                    Fix of cursor in vim
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let &t_SI = "\<esc>[5 q"
let &t_SR = "\<esc>[5 q"
let &t_EI = "\<esc>[2 q"

nnoremap <silent><leader>= :vertical resize +5<cr> 	" resize the vertical window (+)
nnoremap <silent><leader>- :vertical resize -5<cr> 	" resize the vertical window (-)

" spelling mappings
nnoremap ,setd :set spell spelllang=en_us,de<cr>
nnoremap ,seteng :set spell spelllang=en_us<cr>
nnoremap ,setger :set spell spelllang=de<cr>
nnoremap ,setnosp :set nospell<cr>

" mapping special characters for note
inoremap \"o ö
inoremap \"u ü
inoremap \"a ä
inoremap \ss ß
inoremap \"O Ö
inoremap \"U Ü
inoremap \"A Ä

nnoremap <leader><cr> :bd<cr>
nnoremap <leader>. gt
nnoremap <leader>, gT
nnoremap <leader>t :tabedit<cr>

" This is set at the end, because of bugs of vim-plug!
filetype plugin indent off
