" General configurations
"set nocompatible
filetype plugin on
syntax enable
syntax on
set autoindent
set belloff=all
set showcmd				      " Show (partial) command in status line.
set showmatch				    " Show matching brackets.
set ignorecase				  " Do case insensitive matching
set incsearch				    " Incremental search -> while searching you get the results
set autowrite				    " Automatically save before commands like :next and :make
set mouse=a				      " Enable mouse usage (all modes)
set path+=** 				    " searches in the folders if I use :find
set wildmenu 				    " uses a menu so that I can select the file if I use <tab> for completion in
					              " :find and more than one file has been found
set relativenumber			" sets relative numbers
set number				      " sets number at the current line
set clipboard=unnamedplus	" activates clipboard ?
set autoread				    " ? 
"set wrap linebreak
"set shortmess+=c			  " the autocomplete messages won't show below (completion Plugin)
set hidden
set nowrap 				      " code can go down go out of screen
let mapleader=' '
set encoding=utf-8
set backspace=indent,eol,start 		" removing the restriction of the backspace 
                                  " so that it it is possible to delete previously 
                                  " entered code
set noswapfile                    " no swap file is going to get created

set expandtab
set tabstop=2                     " show existing tab with X spaces width
set softtabstop=0                 " width of indentation span
set shiftwidth=2                  " when indenting with '>', use X spaces width

" not too long lines (max. 80 characters)
set colorcolumn=80

" my universal mapping
nnoremap ,unfold :set foldlevel=100<cr>	
nnoremap ,all ggvg
nnoremap ,clear ggVGx
nnoremap <leader>h :wincmd h<cr> 		" switch windows 
nnoremap <leader>j :wincmd j<cr> 		" switch windows
nnoremap <leader>k :wincmd k<cr> 		" switch windows
nnoremap <leader>l :wincmd l<cr> 		" switch windows 

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                    Fix of cursor in vim
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let &t_SI = "\<esc>[5 q"
let &t_SR = "\<esc>[5 q"
let &t_EI = "\<esc>[2 q"

nnoremap <silent><leader>= :vertical resize +5<cr> 	" resize the vertical window (+)
nnoremap <silent><leader>- :vertical resize -5<cr> 	" resize the vertical window (-)

" spelling mappings
nnoremap ,setd :set spell spelllang=en_us,de<cr>
nnoremap ,seteng :set spell spelllang=en_us<cr>
nnoremap ,setger :set spell spelllang=de<cr>
nnoremap ,setnosp :set nospell<cr>

" mapping special characters for note
inoremap \"o ö
inoremap \"u ü
inoremap \"a ä
inoremap \ss ß
inoremap \"O Ö
inoremap \"U Ü
inoremap \"A Ä

let $modulePath='~/lconfig/nvim/modules'
let $pluginsPath='$modulePath/plugins'

source $modulePath/buffersAndTabs.vim

source $modulePath/python.vim
source $modulePath/cpp.vim
source $modulePath/c.vim
source $modulePath/java.vim
source $modulePath/tex.vim
source $modulePath/sh.vim
source $modulePath/markdown.vim
source $modulePath/json.vim

source $pluginsPath/plugins.vim

" This is set at the end, because of bugs of vim-plug!
filetype plugin indent off
